Vagrant.configure("2") do |config|
    config.vm.define "ansible-worker3" do |ansible|
      ansible.vm.box = "debian/buster64"
      ansible.vm.network "public_network", type: "static", ip: "192.168.99.23", dns_search: "notylus.local"
      ansible.vm.hostname = "ansible-worker3"
      ansible.vm.provider "virtualbox" do |v|
        v.name = "ansible-worker3"
        v.memory = 1024
        v.cpus = 1
      end
      ansible.vm.provision :shell do |shell|
        shell.path = "add-on-debian.sh"
      end
    end
  
    config.vm.define "ansible-worker4" do |ansible|
      ansible.vm.box = "debian/buster64"
      ansible.vm.network "public_network", type: "static", ip: "192.168.99.24", dns_search: "domain.local"
      ansible.vm.hostname = "ansible-worker4"
      ansible.vm.provider "virtualbox" do |v|
        v.name = "ansible-worker4"
        v.memory = 1024
        v.cpus = 1
      end
      ansible.vm.provision :shell do |shell|
        shell.path = "add-on-debian.sh"
      end
    end
  
    clients=2
    ram_client=1024
    cpu_client=1
    (1..clients).each do |i|
      config.vm.define "ansible-worker#{i}" do |client|
        client.vm.box = "geerlingguy/centos7"
        client.vm.network "public_network", type: "static", ip: "192.168.99.2#{i}", dns_search: "domain.local"
        client.vm.hostname = "ansible-worker#{i}"
        client.vm.provider "virtualbox" do |v|
          v.name = "ansible-worker#{i}"
          v.memory = ram_client
          v.cpus = cpu_client
        end
        client.vm.provision :shell do |shell|
          shell.path = "add-on-centos.sh"
        end
      end
    end
  end
  
  
  
  